name: Issue Report
description: Report a Problem
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report
  - type: textarea
    id: what-happened
    attributes:
      label: Reproduction Steps
      description: Please provide detailed step by step account of what you did to make the bug happen
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: bug-behaviour
    attributes:
      label: Issue
      description: Please describe the problem
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What were you expecting to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: Are you able to make this happen over and over?
      options:
        - Yes, every time
        - Sometimes
        - No, I could only make it happen once
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser were you using?
      options:
        - Chrome
        - Brave
        - Safari
        - Firefox
        - Edge
        - Internet Explorer
        - Other
    validations:
      required: true
